[package]
name = "ammonia-wasm"
version = "0.2.0"
authors = ["Luca Casonato <hello@lcas.dev>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
ammonia = "3.1.2"
wasm-bindgen = "0.2.74"

[profile.release]
lto = true
opt-level = 3